apiVersion: sro.openshift.io/v1beta1
kind: SpecialResource
metadata:
  name: intel-gpu-kmods
spec:
  namespace: intel-gpu-kmods
  chart:
    name: intel-gpu-kmods
    version: 0.0.1
    repository:
      name: intel-gpu-kmods
      url: cm://intel-gpu-kmods/intel-gpu-kmods-chart-0.0.1
  set:
    kind: Values
    apiVersion: sro.openshift.io/v1beta1
    buildArgs:
    - name: "KMODVER"
      value: "SRO"
  driverContainer:
    source:
      git:
        ref: "rhel85"
        uri: "https://github.com/intel-gpu/intel-gpu-pmt-backports.git"
